### ISSUE TITLE
Spell Check

### ISSUE THREAD

**Issue by souz4s** [jpedrosouza/wheres_my_bus_driver#1]
Spelling correction in the request for permission to use the location. Error location:

`app\src\main\java\com\wheresmybusdriver\android\activitys\LocalizationActivity.java:50:50`

 `.setSettingsDialogTitle("Marning!")` must be changed to `.setSettingsDialogTitle("Warning!")`

**Comment by jpedrosouza** [comment]
Thanks for your collaboration. I will be correcting it as soon as possible. If you feel comfortable, you can make a pull request.

**Comment by souz4s** [comment]
> Thanks for your collaboration. I will be correcting it as soon as possible. If you feel comfortable, you can make a pull request.

I'll do it!
